### ISSUE TITLE
Keine Anzeige von Dokumenten im PDF-Viewer

### ISSUE THREAD

**Issue by Chefredakteur** [the-haps/libertas#25]
**Bitte beschreibe, auf was für einen Bug (Programmfehler) du gestoßen bist:**
Das Dokument der Leseprobe wurde nicht angezeigt. Es war lediglich ein schwarzer/grauer Bildschirm zu sehen. Zoom, Suchfunktion, Seitenwechsel usw. (d.h. alle Funktionen) liefen problemlos, es wurde jedoch schlicht nichts angezeigt. AUSSER ich habe in den Vollbildschirm-Modus gewechselt. Dort war es mir möglich, das Dokument einzusehen bzw. zu zoomen. 

**Bitte beschreibe möglichst genau, was getan hast, um auf den Bug zu stoßen:**
s.o.

**Was hätte eigentlich passieren sollen?**
s.o.

**Screenshots:**
Wenn möglich, füge bitte Screenshots hinzu, die uns bei der Problemlösung des Bugs helfen.
denkbar
**Informationen über dein Gerät:**
- Gerätetyp: [Smartphone oder Computer] - Tablet
- Betriebsystem: [z.B. iOS, Android oder Windows] - Android
- Browser: [z.B. Chrome oder Samsung Internet] - Samsung Internet

**Sonstige Informationen:**
Bitte nenne alles weitere, was für die Problemlösung wichtig sein könnte.

**Comment by Chefredakteur** [comment]
Gilt btw sowohl für angmeldeten als auch unangemeldeten Bereich.

**Comment by CrazyEasy** [comment]
Hast du ein Screenshot? Funktioniert es mit einem anderen Browser (z.B. Google Chrome oder Firefox)?

**Comment by Chefredakteur** [comment]
![Screenshot_20200302-124704_Samsung Internet](https://user-images.githubusercontent.com/59846970/75674031-8bda4f00-5c84-11ea-9516-d7cac9fed4ae.jpg)
Es funktioniert auf Chrome alles absolut reibungslos. Hängt wohl in der Tat mit dem Browser Samsung Internet zsm.

**Comment by CrazyEasy** [comment]
https://mozilla.github.io/pdf.js/web/viewer.html
Wird hier das PDF unter Samsung Internet korrekt dargestellt?
