### ISSUE TITLE
Ausgaben werden nicht angezeigt

### ISSUE THREAD

**Issue by Chefredakteur** [the-haps/libertas#26]
**Bitte beschreibe, auf was für einen Bug (Programmfehler) du gestoßen bist:**
gleiches Situation wie bei vorherig beschriebenen Bug. 

**Bitte beschreibe möglichst genau, was getan hast, um auf den Bug zu stoßen:**

**Was hätte eigentlich passieren sollen?**

**Screenshots:**
Wenn möglich, füge bitte Screenshots hinzu, die uns bei der Problemlösung des Bugs helfen.

**Informationen über dein Gerät:**
- Gerätetyp: [Smartphone oder Computer]
- Betriebsystem: [z.B. iOS, Android oder Windows]
- Browser: [z.B. Chrome oder Samsung Internet]

**Sonstige Informationen:**
Bitte nenne alles weitere, was für die Problemlösung wichtig sein könnte.

**Comment by CrazyEasy** [comment]
Duplicate of #25.
