### ISSUE TITLE
Streichung erklärender Text Passwortänderung

### ISSUE THREAD

**Issue by Chefredakteur** [the-haps/libertas#27]
**Beschreibe möglichst präzise, um welchen Text oder um welche Beschriftung es sich handelt, und wo diese zu finden ist:**
Unter Account --> Passwort ändern --> Aktuelles Passwort

**Wie sollte dieser Text oder die Beschriftung stattdessen lauten:**
- grauer, kleiner Text unter Textfeld streichen - 

**Aus welchem Grund sollte die Beschriftung geändert werden?**
(z.B. Rechtschreibfehler)
überflüssig

**Sonstiges:**
Nenne bitte alles weitere, was für die Verbesserung relevant sein könnte.

**Comment by CrazyEasy** [comment]
Warum sollte der Text überflüssig sein?

**Comment by Chefredakteur** [comment]
Weil es absolut selbsterklärend ist und auch wenn es nicht selbsterklärend wäre, das eine Bedingung ist, die hingenommen werden muss, ganz gleich ob man das versteht oder nicht.

**Comment by CrazyEasy** [comment]
Achso, du meinst "Gib dein aktuelles Passwort ein, um ungewollte Passwortänderungen zu vermeiden."?

**Comment by Chefredakteur** [comment]
Ja
