### ISSUE TITLE
Leseprobe/Ausgabe lesen - Gestaltung

### ISSUE THREAD

**Issue by Chefredakteur** [the-haps/libertas#38]
**Hängt dein Verbesserungsvorschlag mit einem Problem zusammen? Falls ja, beschreibe das Problem:**
(Beispiel: Es frustriert mich immer, wenn...)

**Was würde aus deiner Sicht das Problem lösen? Was wäre dein Verbesserungsvorschlag?**
Die Farbwahl der beiden Buttons „Leseprobe“ und „Ausgabe lesen“ umdrehen, d.h. Leseprobe wird grau hinterlegt bzw. Ausgabe lesen blau. Aktuell ist es verwirrend, weil eine falsche Priorisierung gesetzt wird. 

**Was für alternative Verbesserungsmöglichkeiten kämen für dich in Frage?**

**Sonstiges:**
Teile uns bitte alles mit, was für deinen Verbesserungsvorschlag zusätzlich relevant sein könnte.

**Comment by Chefredakteur** [comment]
Ich meine nicht „Ausgabe lesen“, sondern „Code einlösen“. Sorry, hatte mich falsch erinnert.

**Comment by CrazyEasy** [comment]
Also Code einlösen blau? Und auch nach oben?

**Comment by Chefredakteur** [comment]
Nicht nach oben, Anordnung ist gut. Aber Code einlösen blau, ja.
