### ISSUE TITLE
Warum kann man seinen Account nicht löschen, wenn man Ausgaben besitzt?

### ISSUE THREAD

**Issue by Chefredakteur** [the-haps/libertas#39]
**Hängt dein Verbesserungsvorschlag mit einem Problem zusammen? Falls ja, beschreibe das Problem:**
(Beispiel: Es frustriert mich immer, wenn...)

**Was würde aus deiner Sicht das Problem lösen? Was wäre dein Verbesserungsvorschlag?**

**Was für alternative Verbesserungsmöglichkeiten kämen für dich in Frage?**

**Sonstiges:**
Teile uns bitte alles mit, was für deinen Verbesserungsvorschlag zusätzlich relevant sein könnte.

**Comment by CrazyEasy** [comment]
Kann man aktuell noch, soll man aber in Zukunft nicht mehr können (#14). Wenn jemand seinen Account löscht, wird auch unwiederruflich die Verknüpfung mit den erworbenen Ausgaben gelöscht. Es ist für mich anschließend nicht nachvollziehbar, ob eine Person schonmal eine Ausgabe erworben hatte oder nicht. Um fehlerhaftes "Verschwinden" von Ausgaben durch Accountlöschungen vorzubeugen, soll d.h. die einfache Accountlöschung nur möglich sein, wenn man noch keine Ausgaben besitzt. Sonst wird einen die E-Mail-Adresse von der Schülerzeitung/von mir(?) angezeigt, dass die Leute sich an mich wenden und ich den Account dann lösche, damit sich niemand beschwert, dass er den Zugriff auf seine erworbenen Ausgaben verloren hat.
